[workspace]
members = ["plotters", "plotters-backend", "plotters-bitmap", "plotters-svg"]
default-members = ["plotters"]

[patch.crates-io]
pathfinder_geometry = { commit="05f19143e21a96027de7cf2d60fa47ecd8899d21", git = "https://github.com/theoparis/pathfinder.git" }
